Repository googleapis/python-monitoring, pull requests merged in 2020-05, with the labels that each got.

#21 chore: enable context aware commits
  synth.py
Labels: cla: yes

#22 feat: BREAKING CHANGE: drop support for TimeSeriesQueryLanguageCondition as an alert condition type
  .kokoro/publish-docs.sh
  docs/index.rst
  docs/multiprocessing.rst
  google/cloud/monitoring_v3/gapic/alert_policy_service_client.py
  google/cloud/monitoring_v3/gapic/enums.py
  google/cloud/monitoring_v3/gapic/group_service_client.py
  google/cloud/monitoring_v3/gapic/metric_service_client.py
  google/cloud/monitoring_v3/gapic/notification_channel_service_client.py
  google/cloud/monitoring_v3/gapic/service_monitoring_service_client.py
  google/cloud/monitoring_v3/gapic/transports/group_service_grpc_transport.py
  google/cloud/monitoring_v3/gapic/transports/metric_service_grpc_transport.py
  google/cloud/monitoring_v3/gapic/transports/notification_channel_service_grpc_transport.py
  google/cloud/monitoring_v3/gapic/transports/uptime_check_service_grpc_transport.py
  google/cloud/monitoring_v3/gapic/uptime_check_service_client.py
  google/cloud/monitoring_v3/proto/alert.proto
  google/cloud/monitoring_v3/proto/alert_pb2.py
  google/cloud/monitoring_v3/proto/alert_service_pb2.py
  google/cloud/monitoring_v3/proto/common_pb2.py
  google/cloud/monitoring_v3/proto/dropped_labels_pb2.py
  google/cloud/monitoring_v3/proto/group_pb2.py
  google/cloud/monitoring_v3/proto/group_service_pb2.py
  google/cloud/monitoring_v3/proto/metric_pb2.py
  google/cloud/monitoring_v3/proto/metric_service_pb2.py
  google/cloud/monitoring_v3/proto/mutation_record_pb2.py
  google/cloud/monitoring_v3/proto/notification_pb2.py
  google/cloud/monitoring_v3/proto/notification_service_pb2.py
  google/cloud/monitoring_v3/proto/service_pb2.py
  google/cloud/monitoring_v3/proto/service_service_pb2.py
  google/cloud/monitoring_v3/proto/span_context_pb2.py
  google/cloud/monitoring_v3/proto/uptime_pb2.py
  google/cloud/monitoring_v3/proto/uptime_service_pb2.py
  synth.metadata
  synth.py
Labels: cla: yes, context: full

#32 chore: update templates (via synth)
  .kokoro/release.sh
  google/cloud/monitoring_v3/proto/common_pb2.py
  synth.metadata
Labels: cla: yes, context: partial
